name: Github Actions Example

on:
	pull,request:
	push:
		branches: [master,develop]
			
jobs:
	test:
		-name: Running Unit test
		 runs-on: ubuntu-latest
		
		steps:
		- uses: actions/checout@v1
		- name: Use Node.js ${{matrix.node-version}}
		  uses: actions/setup-node@v1
		  with:
			node-version: ${{matrix.node-version}}
		- name: Install
		  run: npm install
		- name: Test
		  run: npm test
